[package]
name = "num_opt_2d"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
getset = "0.1.3"
nalgebra = "0.33.2"
nannou = "0.19.0"
num-traits = "0.2.19"
serde_json = "1.0.133"
